services:
  flask_app:
    build: .
    network_mode: bridge
    ports:
      - "${HOST_PORT}:5000"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_APP: app.py
      APP_PASSWORD: ${APP_PASSWORD}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      DOMAIN: ${DOMAIN}
      FLASK_HOST: ${FLASK_HOST}

